version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet build
      - dotnet publish -c release -o ./build_output CICDDemo/CICDDemo.csproj
artifacts:
  files:
    - './CICDDemo/build_output/**.*'
    - './CICDDemo/wwwroot/**/*'
    
